- source/mir/random/engine/linear_congruential.d
> Properly sanitize seeds for Park–Miller engines

- source/mir/random/engine/mersenne_twister.d
Behavior is like the reference implementation's init_by_array,
not like Phobos std.random.MersenneTwisterEngine's seed(Range).
> Allow seeding MersenneTwisterEngine with arrays/ranges

- source/mir/random/engine/xorshift.d
Discussion https://github.com/libmir/mir-random/issues/30
> Add Xorshift1024StarPhi generator

- source/mir/random/package.d
Includes changes required for `unittest`s to pass.
Part of ongoing effort https://github.com/libmir/mir-random/issues/40
> `@safe unittest` for every function in mir.random.package

- README.md
- index.d
- source/mir/random/engine/pcg.d
- source/mir/random/engine/xorshift.d
- source/mir/random/package.d
Fixes https://github.com/libmir/mir-random/issues/48 and makes misc. improvements.
> Improve documentation

- dub.json
- source/mir/random/engine/package.d
Fixes issue https://github.com/libmir/mir-random/issues/52
> Enable GETRANDOM on non-X86/X86_64 linux

- source/mir/random/engine/splitmix.d
Now every SplitMixEngine is a Phobos UniformRNG and the code is simpler.
> Remove unnecessary "output_previous" option from SplitMixEngine

- source/mir/random/variable.d
Ensure isRandomVariable is true for each type in mir.random.variable
> Ensure isRandomVariable is true for each type in mir.random.variable

- source/mir/random/ndvariable.d
- source/mir/random/package.d
- source/mir/random/variable.d
Proposal: Allow functions to accept either ref or ptr to generator. I don't immediately see a problem with this idea but I could be overlooking something.
> Proposal: Allow functions to accept either ref or ptr to generator

- doc/Makefile
- doc/custom.ddoc
- doc/run_examples_custom.js
Similar to https://github.com/libmir/mir-algorithm/pull/122, but with the small improvement of automatically injecting the latest version into the JavaScript source code. I will change run.dlang.io, s.t. it will automatically fetch new updates for patch releases every day.
> Automatically inject the latest version

- source/mir/random/algorithm.d
The `@safe` way is still there, but now it is an option to do the non-safe way if the programmer prefers the nicer-looking syntax.
Current way, `@safe`:
```d
auto rng = Random(unpredictableSeed);
auto sample = range!rng
(NormalVariable!double(0, 1))
.take(10)
.array;
```
Re-enabled old way, `@system`:
```d
auto rng = Random(unpredictableSeed);
auto sample = rng
.range(NormalVariable!double(0, 1))
.take(10)
.array;
```
The reason for `__traits(compiles, { static assert(isSaturatedRandomEngine!(typeof(gen))); })` in some places instead of `isSaturatedRandomEngine!(typeof(gen))` is to avoid compilation errors.
The `@system` annotations for the alternative overrides are not necessary for the compiler. They're just for the benefit of humans reading the library.
> Re-enable passing generators by ref in mir.random.algorithm

- source/mir/random/algorithm.d
- source/mir/random/flex/package.d
- source/mir/random/ndvariable.d
- source/mir/random/package.d
- source/mir/random/variable.d
1. remove default params from constructors
2. add conventions functions for variables construction
3. add randomSlice
4. rework API for complex numbers in `field`
5. add default value for `field`
> add/rework API

- source/mir/random/ndvariable.d
- source/mir/random/variable.d
Also rename betaVariable to betaVar for consistency.
> Create alias xxxVariable for every xxxVar

- source/mir/random/package.d
[LDC 1.8.0 supports llvm_expect in CTFE](https://github.com/ldc-developers/ldc/releases/tag/v1.8.0) so now the ugly code duplication can be removed.
> Cleanup duplicated code in randIndex

- source/mir/random/engine/package.d
https://msdn.microsoft.com/en-us/library/cc230318.aspx
My guess is that when `ULONG_PTR` had to be redefined as `ulong` instead of `uint` the same was done to `DWORD` by accident.
> Microsoft Windows DWORD is uint not ulong

- source/mir/random/engine/package.d
In `fallBackseed`, on x86-64 use RDTSC for ticks, on Alpha use `ldc.intrinsics.readcyclecounter`. Also remove unnecessary failure check for `clock_gettime`.
> In fallBackseed, on x86-64 use RDTSC for ticks, on Alpha use RPCC.

- source/mir/random/engine/package.d
A legacy arc4random should not be used when cryptographic security is required but is suitable for `unpredictableSeed`. Phobos does this too these days (https://github.com/dlang/phobos/pull/6267/files).
> Legacy (ARC4) arc4random is suitable for unpredictableSeed

- source/mir/random/engine/package.d
Assume getrandom is available to start. If getrandom fails with `errno == ENOSYS` switch to the /dev/random implementation and don't try getrandom again. This approach simplifies the code and performs less work in the typical case where the Linux version >= 3.17.
> Lazily detect Linux getrandom support instead of explicit version check at startup

- .travis.yml
- examples/flex_plot/flex_common_pack/dub.json
Use a newer version which does not depend on class deallocator.
> Upgrade pyd to v0.13.0

- source/mir/random/engine/pcg.d
> Add .save property to PermutedCongruentialEngine when stream type is stream_t.specific

- source/mir/random/engine/pcg.d
Quick start example similar to those for Mersenne Twister and Xoshiro.
> Add pcg example
