libmir/mir-random

source/mir/random/engine/mersenne_twister.d

This comment covers the essentials of how `opCall` is structured: the two separate procedures that are carried out, and the importance of them being interwoven rather than performed sequentially.
@9il hope this is useful -- I felt that your explanation of the design choices made here shouldn't be limited to a forum post.

Add an explanatory comment to MersenneTwisterEngine.opCall

---

source/mir/random/engine/mersenne_twister.d

The original template signature diverges from the C++11 standard both in names and types of template parameters.  While not producing a functional difference, matching the standard allows for a less ambiguous declaration and makes for easier adaptation on the part of users used to C++ code.
These patches also introduce the previously-missing "initialization multiplier" template parameter `f`.  Since the correct value for this parameter is not solely dependent on the unsigned integer type in use, the original `static if` would not have covered all possible instantiations of the generator.
Finally, a basic unittest has been added for `Mt19937_64` both to validate the generator and ensure that its behaviour does not change as a result of these updates.

Update MersenneTwisterEngine template signature to match C++11 standard

---

source/mir/random/engine/mersenne_twister.d
source/mir/random/engine/package.d

This patch corrects the usage of the `Mt19937` symbol to bring it in line with standard definitions for the Mersenne Twister engine, where MT19937 is the name of the standard 32-bit generator and MT19937-64 is the name of the standard 64-bit generator.
The now-obsolete `Mt19937_32` symbol has been removed.
This brings mir.random's API in line with the C++11 standard where the similar template instantiations are called `mt_19937` and `mt_19937_64`.
The `Random` symbol has been updated to alias to `Mt19937` on 32-bit systems and `Mt19937_64` on 64-bit systems.  Some extra example tests have been added to provide separate usage examples for `Mt19937` and `Mt19937_64`.
Fixes libmir/mir-random#19.

Use Mt19937 only for 32-bit generator

---

source/mir/random/algorithm.d
source/mir/random/engine/package.d
source/mir/random/engine/pcg.d
source/mir/random/package.d

std.traits.ReturnType!T doesn't work if T.opCall is a function template.
This meant that isSaturatedRandomEngine and a few other things would
not compile when given the mir.random.engine.pcg generators as template
arguments.

Fix isSaturatedRandomEngine when opCall is a function template

---

source/mir/random/engine/package.d

Also use it for genRandomNonBlocking. On Mac OS X /dev/random does not
block so also use arc4random_buf for genRandomBlocking.

Use arc4random_buf for unpredictableSeed when known to be good

---

source/mir/random/engine/pcg.d

The increment is supposed to be based on the address of the object
but that is not what the code did.

Fix increment of PCG unique_stream

---

source/mir/random/engine/linear_congruential.d
source/mir/random/engine/package.d
source/mir/random/engine/xorshift.d
source/mir/random/package.d

The output of some PRNGs has output that is higher quality in the the high bits than the low bits.

Prefer high bits

---

source/mir/random/package.d
source/mir/random/variable.d

`@safe unittest` for every function in mir.random.variable
Requires mir.random.package to have been made `@safe`
Part of ongoing effort https://github.com/libmir/mir-random/issues/40

`@safe unittest` for every function in mir.random.variable

---

source/mir/random/engine/pcg.d
source/mir/random/engine/xorshift.d
source/mir/random/package.d

This allows the new engines to be used with legacy libraries that expect
Phobos-style random number generators. It turns out that these most
recent additions are the only engines currently in the library that can
conveniently implement `front` without re-working.

Add compatibility with Phobos random interface to PCG and xoroshiro128+

---

bench/randindex_bench.d
dub.json
source/mir/random/package.d

[Full explanation on Daniel Lemire's blog.](https://lemire.me/blog/2016/06/27/a-fast-alternative-to-the-modulo-reduction/) [Another entry covers bias correction when using this method.](https://lemire.me/blog/2016/06/30/fast-random-shuffling/)
If our `gen()` produces `ulong` and we want to convert this to a `uint` in range `0 .. m`, instead of
```
(cast(uint) gen()) % m
```
we can do:
```
cast(uint) (((gen() >>> 32) * m) >>> 32)
```
which replaces a modulo operation with a multiplication and some shifts.
I put a benchmark for this at [bench/randindex_bench.d](https://github.com/n8sh/mir-random/blob/9fe19f33766cdce7baa00b3b024d5c0d2e5bd29b/bench/randindex_bench.d). The performance gain was minor, but the result persisted when running the benchmark repeatedly.
----
**EDIT:**
As @9il points …

Use Daniel Lemire’s fast alternative to modulo reduction

---

source/mir/random/engine/package.d

https://github.com/libmir/mir-random/issues/49
https://github.com/libmir/mir/issues/390

Fix Linux non-x86/x86_64 compilation failure

---

source/mir/random/engine/package.d

**Old:**
`genRandomBlocking(void* ptr, size_t len) @trusted`
**New:**
`genRandomBlocking(void* ptr, size_t len) @system`
`genRandomBlocking(ubyte[] buf) @trusted`

Change genRandom(Non)Blocking safety and add version that takes buffer

---

dub.json
source/mir/random/engine/package.d

For issue https://github.com/libmir/mir-random/issues/41
**(EDIT: below info is outdated. New names are `rne`, `threadLocal!Engine`, `threadLocalPtr!Engine`, and `threadLocalInitialized!Engine`).**
Includes
```
rndGen
threadLocal!Engine
_rawThreadLocal!Engine
```
but I'm not sure it's really desirable to have all of those. `_rawThreadLocal` exposes the static field just so the compiler can tell that it's safe to take the address, if for some reason you need the address of the engine. If there's a way to make the compiler not complain `"cannot take address of ref return of threadLocal() in @safe function"` that would be better.
Also made the documentation look a bit nicer while I was making changes.

Add thread-local randoms except when D_betterC

---

dub.json
source/mir/random/algorithm.d

Includes changes required for `unittest`s to pass.
Requires mir.random.package to have been made `@safe`
Part of ongoing effort https://github.com/libmir/mir-random/issues/40

`@safe unittest` for every function in mir.random.algorithm

---

source/mir/random/engine/package.d

Pinging @wilzbach - do we have a reason to use `genRandomBlocking` instead of `genRandomNonBlocking`?

unpredictableSeed: change to non-blocking

---

source/mir/random/algorithm.d
source/mir/random/engine/package.d

In mir.random.algorithm examples
use TLS instead of `new` when we need a `@safe`
pointer to a random number generator.
`setThreadLocalSeed` doesn't enable anything new but
is convenient.

Use TLS in examples & add setThreadLocalSeed

---

source/mir/random/flex/internal/area.d
source/mir/random/flex/internal/transformations.d
source/mir/random/flex/internal/types.d
source/mir/random/ndvariable.d

Part of ongoing effort https://github.com/libmir/mir-random/issues/40
`mir.random.flex.internal.package` doesn't yet have coverage because `mir.math.sum.Summator` is unsafe.

`@safe unittest` for ndvariable and flex

---

source/mir/random/package.d

`jump` example didn't work properly (sequence is different from non-wrapped engine) because underlying engine doesn't know to update opCall. Other possible methods would have similar problems so it is better to remove `alias this`.
`.engine` property is still available for directly calling methods of Engine.

Remove 'alias this' from PhobosRandom wrapper

---

.travis.yml

[The last build](https://travis-ci.org/libmir/mir-random/builds/329747617) waited for 11 hours without starting any of the OS X builds. DMD has also disabled Travis testing for this reason (https://github.com/dlang/dmd/pull/7721).

Temporarily disable osx builds in Travis CI because of very long wait times

---

source/mir/random/engine/package.d

`unpredictableSeed` includes a block of fallback code which is seldom called. Moving this to a separate function and preventing it from being inlined will improve cache-friendliness.

Un-inline fallback code in unpredictableSeed

---

source/mir/random/engine/xorshift.d

Fix a mistake I made in the xorshift* template. Fortunately does not affect either of the predefined xorshift* generators, since the code branch is only taken when the internal array is length 2 or 3. (At length 1 there is no need to move items within the array, and at lengths 4 and greater an index is used instead.)

Fix disallowed overlapping slice assignment in 2-word and 3-word XorshiftStar

---

README.md
index.d
source/mir/random/engine/xorshift.d

Make XorshiftEngine template work with any UIntType while maintaining full backward compatibility. Unittests in `mir.random.algorithm` verified that the results did not change.

Make XorshiftEngine template work with any UIntType

---

README.md

This time I used "~>0.4" for the links, s.t. they don't need frequent updates.
("~>0.4" matches alll 0.X, whereas `~>0.3.5` only matches 0.3.x)

Update run.dlang.io links

---

source/mir/random/flex/internal/calc.d

Currently `std.math.tan/atan` are calculated using extended precision but dlang/phobos#6272 adds specializations for `float` and `double`. To pass current unittests we need to explicitly use double or extended precision `tan`/`atan` even when `S` is a single-precision.

In arcmean use at least double precision tan/atan (due to dlang/phobos#6272)

---

source/mir/random/flex/internal/area.d

For dlang/phobos#6272 which slightly changes result of `std.math.exp`. _Not 100% sure if changing this test is the right thing to do!_
Now on all platforms `fpEqual` requires all but the last two bits of the mantissas to match. Previously (only) with DMD on X86_64 `fpEqual` was exact equality. (The current test does not require exact equality with LDC, but I checked and the test still passes on X86_64 with LDC if `fpEqual` is changed to require exact equality.)

Alter unittest flex `fpEqual` to allow dlang/phobos#6272

---

README.md
index.d
source/mir/random/engine/xorshift.d

`xoshiro256**` is described in the paper [_Scrambled Linear Pseudorandom Number Generators_ (Blackman & Vigna, 2018)](https://arxiv.org/pdf/1805.01407.pdf).
From an end-user's standpoint I think the pertinent details are that `xoshiro256**` is 15% slower than [`xoroshiro128+`](https://en.wikipedia.org/wiki/Xoroshiro128%2B) but its low bits don't fail binary rank tests, and `xoshiro256**` is fully (4-dimensionally) equidistributed while `xoroshiro128+` is only 1-dimensionally equidistributed, and (to state the obvious)  `xoshiro256**` has 256 bits of state and a 2^^256-1 period instead of 128 bits of state and a 2^^128-1 period.

Add Xoshiro256StarStar (xoshiro256**) generator

---

README.md
index.d
source/mir/random/engine/xorshift.d

Most of the recently-added engines have been 64-bit oriented. `xoshiro128**` is a 32-bit one.

Add Xoshiro128StarStar_32 and make XoshiroEngine template

---

.travis.yml

```
Buildkite is used by DMD to ensure downstream projects are not broken.
Using meson here forces Buildkite agents to depend on meson.
While it would be possible to do so, that requires some work and coordination,
and might get delayed. In the meantime, just disable meson when buildkit is defined.
```
If possible, I'd like to get this in v1.0.1, as we check out the latest release.

Don't run meson build with Buildkite

---

source/mir/random/package.d

I assume the documentation is wrong, but if it is not then the behavior must be fixed instead.

Fix documentation of rand!IntType: min result is IntType.min not 0

---

README.md
source/mir/random/algorithm.d

- Rework API for `randomSlice` (full rework), `shuffle` (accepts only Slice), `sample` (fix param order).
- Remove `range` and `field` because they can be either secure or consistent with Phobos/Mir.
- Update examples in the readme.

fix issue #99

---

index.d
source/mir/random/engine/xorshift.d
source/mir/random/engine/xoshiro.d
source/mir/random/package.d

The moved generators are publicly imported by `mir.random.engine.xorshift` so existing programs expecting them there will still work.

Split mir.random.engine.xoshiro from mir.random.engine.xorshift

---

source/mir/random/ndvariable.d
source/mir/random/variable.d

In `mir.random.variable` this applies to every variable except Bernoulli2Variable, LogNormalVariable, NormalVariable, & StudentTVariable. Also some `min` and `max` properties were affected.
In `mir.random.nvariable` this applies to DirichletVariable & SimplexVariable. The `const` annotation was not applied to the `opCall` of MultivariateNormalVariable or SphereVariable in case they are changed to have a member NormalVariable.

Mark mir.random.variable & mir.random.ndvariable opCall as const when possible

---

README.md
source/mir/random/engine/package.d

Fewer letters and matches new overload in Phobos std.random (https://github.com/dlang/phobos/pull/6580).

Rename unpredictableSeedOf!UIntType to unpredictableSeed!UIntType

---

dub.sdl
source/mir/random/ndvariable.d

I have ported this from GSL as described on issue #117.
it has been adapted to Mir-random API and has a simple unittest which are passing.
There is a minor deviation from the way other ndvariables in that the `opCall` is not void, but rather returns the result expected. I try but could not make it alter the result variable passed in in the outer scope, even though my implementation follows exactly the other variable's implementations. The only difference is that multinomial returns an array of long integers instead of doubles.
If there's a way to fix this, please let me know and I'll change the code, but as it is  the function works correctly. It is worth pointing out that the `opCall` of the scalar random variables, defined in `variable.d`, are also not void, returning the results …

Implementation of Multinomial random variable

---

source/mir/random/ndvariable.d

to let user to check the input before constructing a MultivariateNormalVariable instance. In other case if the input is wrong `assert(0);` terminates the program.

Make MultivariateNormalVariable.cholesky public

---

dub.sdl

```
Currently, programs depending on mir-random and mir-algorithm are broken
(e.g. lubeck) because of the version specification.
While it looks very much like a bug in dub, there doesn't seem to be a
tangible reason to have the current version restriction:
if v1.0.0 works, any v1.x.y should work as well.
```
Currently Buildkite builds are broken because of this.

Correct version dependency on mir-core

---

examples/flex_plot/test_arcsine.d
examples/flex_plot/test_beta.d
examples/flex_plot/test_density_at_boundaries.d
examples/flex_plot/test_density_with_poles.d
examples/flex_plot/test_different_c_values.d
examples/flex_plot/test_double_dist.d
examples/flex_plot/test_gamma.d
examples/flex_plot/test_inflection_point_at_boundary.d
examples/flex_plot/test_near_extrema.d
examples/flex_plot/test_normal.d
source/mir/random/flex/internal/calc.d

```
Allow the code to compile with '-preview=in'.
In the test code, 'in ref' was replaced with simply 'in',
as the test code isn't much affected by the loss of 'ref'.
However, for the library code, the original meaning was retained.
```
In support of https://github.com/dlang/dmd/pull/11632 (so I can ensure projects compile and the switch is usable).

-preview=in: Replace 'in ref' with either 'in' or 'const scope ref'
